export const PROFILE_ICON = '[data-testid="navbar-profile-icon"]'
export const COLLECTION_LINK = '[data-testid="navbar-collection-link"]'
export const CART_LINK = '[data-testid="navbar-cart-link"]'
export const CART_COUNT = '[data-testid="navbar-cart-count"]'
export const SEARCH_ICON = '[data-testid="navbar-search-icon"]'
